name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: Login in Docker Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCRIOTOKEN }}
      - name: Login in Dockerhub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker pull and push
        run: |
          set -o pipefail
          set -e
          images=(
            k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
            k8s.gcr.io/ingress-nginx/controller:v0.35.0
            k8s.gcr.io/pause:3.6
            registry.k8s.io/ingress-nginx/controller:v1.3.0
            registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1
            k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
            k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
            k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
            k8s.gcr.io/sig-storage/snapshot-controller:v3.0.3
            k8s.gcr.io/sig-storage/snapshot-controller:v4.0.0
            k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
            k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
            k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
            k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
            k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1
            k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0
            k8s.gcr.io/metrics-server/metrics-server:v0.6.1
            gcr.io/google-samples/hello-app:1.0
            ghcr.io/dexidp/dex:v2.32.0
            gcr.io/cadvisor/cadvisor:v0.45.0
            registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0
            k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.6.0
            registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.2
            registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.0
            registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
            gcr.io/distroless/static:nonroot
          )
          for image in ${images[@]}; do 
            rest_name=$(echo $image | rev | cut -d'/' -f1 | rev)
            docker manifest inspect sl01248/$rest_name > /dev/null && continue
            docker pull $image
            docker tag $image sl01248/$rest_name
            docker push sl01248/$rest_name
          done
